version: '3.8'

services:
  identity-db:
    image: postgres:15-alpine
    container_name: echora-identity-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: identitypassword
      POSTGRES_DB: echora_identity
    ports:
      - "5432:5432"
    volumes:
      - identity_db_data:/var/lib/postgresql/data

  complaint-db:
    image: postgres:15-alpine
    container_name: echora-complaint-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: complaintpassword
      POSTGRES_DB: echora_complaint
    ports:
      - "5433:5432"
    volumes:
      - complaint_db_data:/var/lib/postgresql/data

  identity-service:
    build: ./identity-service
    container_name: echora-identity-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=identity-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=identitypassword
      - DB_NAME=echora_identity
      - JWT_SECRET=identity_jwt_secret_key_12345
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=5
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=bhavanac1905@gmail.com
      - EMAIL_PASS=apwr yvzu bqhj pwxg
      - NODE_ENV=production
    depends_on:
      - identity-db

  complaint-service:
    build: ./complaint-service
    container_name: echora-complaint-service
    restart: always
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DB_HOST=complaint-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=complaintpassword
      - DB_NAME=echora_complaint
      - JWT_SECRET=complaint_jwt_secret_key_54321
      - IDENTITY_SERVICE_URL=http://identity-service:3001
      - NODE_ENV=development
    depends_on:
      - complaint-db
      - identity-service

  frontend:
    build: ./frontend
    container_name: echora-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_IDENTITY_API_URL=http://localhost:3001
      - VITE_COMPLAINT_API_URL=http://localhost:3003
    depends_on:
      - identity-service
      - complaint-service

volumes:
  identity_db_data:
  complaint_db_data:
